production:
  adapter: postgresql
  encoding: unicode
  database: tweeter_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tweeter_development
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: tweeter_development
  pool: 5

